kind: pipeline
name: ci
type: docker

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  ref:
    include:
      - refs/tags/*

steps:
  - name: Go build
    image: golang:1.20
    volumes:
      - name: golang_cache
        path: /go/pkg/mod
      - name: golang_build_cache
        path: /root/.cache/go-build
    commands:
      - cd ./scripts/
      - ./build.sh

  - name: Publish plugin
    image: plugins/docker
    settings:
      registry: https://registry.nas.local.abbottland.io
      username: pbabbott
      password:
        from_secret: REGISTRY_PASSWORD
      mirror: https://registry-mirror.nas.local.abbottland.io
      repo: registry.nas.local.abbottland.io/envbuilder
      auto_tag: true
      dockerfile: ./scripts/Dockerfile
      context: ./scripts/  

volumes:
  - name: golang_build_cache
    host:
      path: /var/lib/cache/golang_build_cache
  - name: golang_cache
    host:
      path: /var/lib/cache/golang_cache
  - name: docker_daemon
    host:
      path: /var/run/docker.sock