kind: pipeline
name: ci
type: docker

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - "*"

steps:
  - name: run build
    image: golang:1.20
    volumes:
      - name: golang_cache
        path: /tmp/golang_cache
    commands:
      - echo GOPATH $GOPATH
      - ./scripts/build.sh

  - name: Container Build
    image: plugins/docker
    volumes:
      - name: docker_daemon
        path: /var/run/docker.sock
    commands:
      - ./scripts/docker-build.sh

volumes:
  - name: golang_cache
    host:
      path: /var/lib/cache/golang_cache
  - name: docker_daemon
    host:
      path: /var/run/docker.sock